services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: 'eliasablan.dev'
    image: 'ghcr.io/eliasablan/eliasablan.dev:latest'
    ports:
      - '3001:3000'
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
      - .env.local
  prod:
    platform: 'linux/amd64'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'eliasablan'
    image: 'ghcr.io/eliasablan/eliasablan.prod:latest'
    ports:
      - '5001:3000'
    env_file:
      - .env
      - .env.local
