version: '3'

services:
  next-app:
    container_name: next-app
    build:
      context: ./next-app
      dockerfile: dev.Dockerfile

    # Set environment variables directly in the docker-compose file
    environment:
      RESEND_API_KEY: ${RESEND_API_KEY}
      VERCEL_URL: ${VERCEL_URL}
      NEXT_PUBLIC_SANITY_PROJECT_ID: ${NEXT_PUBLIC_SANITY_PROJECT_ID}
      NEXT_PUBLIC_SANITY_DATASET: ${NEXT_PUBLIC_SANITY_DATASET}
      SANITY_REVALIDATE_SECRET: ${SANITY_REVALIDATE_SECRET}

    # Set environment variables based on the .env file
    env_file:
      - .env.local
    volumes:
      - ./next-app/src:/app/src
      - ./next-app/public:/app/public
    restart: always
    ports:
      - 3000:3000
