version: '3'

services:
  next-app:
    container_name: next-app
    build:
      context: ./next-app
      dockerfile: prod.Dockerfile
      args:
        RESEND_API_KEY: ${RESEND_API_KEY}
        VERCEL_URL: ${VERCEL_URL}
        NEXT_PUBLIC_SANITY_PROJECT_ID: ${NEXT_PUBLIC_SANITY_PROJECT_ID}
        NEXT_PUBLIC_SANITY_DATASET: ${NEXT_PUBLIC_SANITY_DATASET}
        SANITY_REVALIDATE_SECRET: ${SANITY_REVALIDATE_SECRET}

    restart: always
    ports:
      - 5001:3000
