services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'eliasablan.dev'
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env.local
  prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: 'eliasablan'
    ports:
      - '5001:3000'
    env_file:
      - .env
      - .env.local
